#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPSStorageMonitor
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SPSEnvision")]
	public partial class SPSDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertSPS_Storage(SPS_Storage instance);
    partial void UpdateSPS_Storage(SPS_Storage instance);
    partial void DeleteSPS_Storage(SPS_Storage instance);
    #endregion
		
		public SPSDBDataContext() : 
				base(global::SPSStorageMonitor.Properties.Settings.Default.SPSEnvisionConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public SPSDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SPSDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SPSDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SPSDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<SPS_Storage> SPS_Storage
		{
			get
			{
				return this.GetTable<SPS_Storage>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SPS_Storage")]
	public partial class SPS_Storage : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _ID;
		
		private string _WebName;
		
		private string _WebID;
		
		private string _WebUrl;
		
		private string _ListName;
		
		private string _ListID;
		
		private string _ListUrl;
		
		private System.Nullable<int> _FolderNumber;
		
		private System.Nullable<int> _FileNumber;
		
		private System.Nullable<decimal> _Storage;
		
		private string _Owners;
		
		private System.Nullable<int> _DesitionType;
		
		private System.Nullable<System.DateTime> _Created;
		
		private string _CreatorAccount;
		
		private string _CreatorUserName;
		
		private string _ParentWebID;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(long value);
    partial void OnIDChanged();
    partial void OnWebNameChanging(string value);
    partial void OnWebNameChanged();
    partial void OnWebIDChanging(string value);
    partial void OnWebIDChanged();
    partial void OnWebUrlChanging(string value);
    partial void OnWebUrlChanged();
    partial void OnListNameChanging(string value);
    partial void OnListNameChanged();
    partial void OnListIDChanging(string value);
    partial void OnListIDChanged();
    partial void OnListUrlChanging(string value);
    partial void OnListUrlChanged();
    partial void OnFolderNumberChanging(System.Nullable<int> value);
    partial void OnFolderNumberChanged();
    partial void OnFileNumberChanging(System.Nullable<int> value);
    partial void OnFileNumberChanged();
    partial void OnStorageChanging(System.Nullable<decimal> value);
    partial void OnStorageChanged();
    partial void OnOwnersChanging(string value);
    partial void OnOwnersChanged();
    partial void OnDesitionTypeChanging(System.Nullable<int> value);
    partial void OnDesitionTypeChanged();
    partial void OnCreatedChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedChanged();
    partial void OnCreatorAccountChanging(string value);
    partial void OnCreatorAccountChanged();
    partial void OnCreatorUserNameChanging(string value);
    partial void OnCreatorUserNameChanged();
    partial void OnParentWebIDChanging(string value);
    partial void OnParentWebIDChanged();
    #endregion
		
		public SPS_Storage()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WebName", DbType="NVarChar(200)")]
		public string WebName
		{
			get
			{
				return this._WebName;
			}
			set
			{
				if ((this._WebName != value))
				{
					this.OnWebNameChanging(value);
					this.SendPropertyChanging();
					this._WebName = value;
					this.SendPropertyChanged("WebName");
					this.OnWebNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WebID", DbType="NVarChar(50)")]
		public string WebID
		{
			get
			{
				return this._WebID;
			}
			set
			{
				if ((this._WebID != value))
				{
					this.OnWebIDChanging(value);
					this.SendPropertyChanging();
					this._WebID = value;
					this.SendPropertyChanged("WebID");
					this.OnWebIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WebUrl", DbType="NVarChar(500)")]
		public string WebUrl
		{
			get
			{
				return this._WebUrl;
			}
			set
			{
				if ((this._WebUrl != value))
				{
					this.OnWebUrlChanging(value);
					this.SendPropertyChanging();
					this._WebUrl = value;
					this.SendPropertyChanged("WebUrl");
					this.OnWebUrlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ListName", DbType="NVarChar(50)")]
		public string ListName
		{
			get
			{
				return this._ListName;
			}
			set
			{
				if ((this._ListName != value))
				{
					this.OnListNameChanging(value);
					this.SendPropertyChanging();
					this._ListName = value;
					this.SendPropertyChanged("ListName");
					this.OnListNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ListID", DbType="NVarChar(50)")]
		public string ListID
		{
			get
			{
				return this._ListID;
			}
			set
			{
				if ((this._ListID != value))
				{
					this.OnListIDChanging(value);
					this.SendPropertyChanging();
					this._ListID = value;
					this.SendPropertyChanged("ListID");
					this.OnListIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ListUrl", DbType="NVarChar(500)")]
		public string ListUrl
		{
			get
			{
				return this._ListUrl;
			}
			set
			{
				if ((this._ListUrl != value))
				{
					this.OnListUrlChanging(value);
					this.SendPropertyChanging();
					this._ListUrl = value;
					this.SendPropertyChanged("ListUrl");
					this.OnListUrlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FolderNumber", DbType="Int")]
		public System.Nullable<int> FolderNumber
		{
			get
			{
				return this._FolderNumber;
			}
			set
			{
				if ((this._FolderNumber != value))
				{
					this.OnFolderNumberChanging(value);
					this.SendPropertyChanging();
					this._FolderNumber = value;
					this.SendPropertyChanged("FolderNumber");
					this.OnFolderNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileNumber", DbType="Int")]
		public System.Nullable<int> FileNumber
		{
			get
			{
				return this._FileNumber;
			}
			set
			{
				if ((this._FileNumber != value))
				{
					this.OnFileNumberChanging(value);
					this.SendPropertyChanging();
					this._FileNumber = value;
					this.SendPropertyChanged("FileNumber");
					this.OnFileNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Storage", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Storage
		{
			get
			{
				return this._Storage;
			}
			set
			{
				if ((this._Storage != value))
				{
					this.OnStorageChanging(value);
					this.SendPropertyChanging();
					this._Storage = value;
					this.SendPropertyChanged("Storage");
					this.OnStorageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Owners", DbType="NVarChar(500)")]
		public string Owners
		{
			get
			{
				return this._Owners;
			}
			set
			{
				if ((this._Owners != value))
				{
					this.OnOwnersChanging(value);
					this.SendPropertyChanging();
					this._Owners = value;
					this.SendPropertyChanged("Owners");
					this.OnOwnersChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DesitionType", DbType="Int")]
		public System.Nullable<int> DesitionType
		{
			get
			{
				return this._DesitionType;
			}
			set
			{
				if ((this._DesitionType != value))
				{
					this.OnDesitionTypeChanging(value);
					this.SendPropertyChanging();
					this._DesitionType = value;
					this.SendPropertyChanged("DesitionType");
					this.OnDesitionTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Created", DbType="DateTime")]
		public System.Nullable<System.DateTime> Created
		{
			get
			{
				return this._Created;
			}
			set
			{
				if ((this._Created != value))
				{
					this.OnCreatedChanging(value);
					this.SendPropertyChanging();
					this._Created = value;
					this.SendPropertyChanged("Created");
					this.OnCreatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatorAccount", DbType="NVarChar(50)")]
		public string CreatorAccount
		{
			get
			{
				return this._CreatorAccount;
			}
			set
			{
				if ((this._CreatorAccount != value))
				{
					this.OnCreatorAccountChanging(value);
					this.SendPropertyChanging();
					this._CreatorAccount = value;
					this.SendPropertyChanged("CreatorAccount");
					this.OnCreatorAccountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatorUserName", DbType="NVarChar(50)")]
		public string CreatorUserName
		{
			get
			{
				return this._CreatorUserName;
			}
			set
			{
				if ((this._CreatorUserName != value))
				{
					this.OnCreatorUserNameChanging(value);
					this.SendPropertyChanging();
					this._CreatorUserName = value;
					this.SendPropertyChanged("CreatorUserName");
					this.OnCreatorUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentWebID", DbType="NVarChar(50)")]
		public string ParentWebID
		{
			get
			{
				return this._ParentWebID;
			}
			set
			{
				if ((this._ParentWebID != value))
				{
					this.OnParentWebIDChanging(value);
					this.SendPropertyChanging();
					this._ParentWebID = value;
					this.SendPropertyChanged("ParentWebID");
					this.OnParentWebIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
