#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Envision.SPS.DataAccess
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="WSS_Content")]
	public partial class SPDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertAllDocs(AllDocs instance);
    partial void UpdateAllDocs(AllDocs instance);
    partial void DeleteAllDocs(AllDocs instance);
    #endregion
		
		public SPDBDataContext() : 
				base(global::Envision.SPS.DataAccess.Properties.Settings.Default.WSS_ContentConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public SPDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SPDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SPDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SPDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<AllDocs> AllDocs
		{
			get
			{
				return this.GetTable<AllDocs>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AllDocs")]
	public partial class AllDocs : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _Id;
		
		private System.Guid _SiteId;
		
		private string _DirName;
		
		private string _LeafName;
		
		private byte _Level;
		
		private System.Guid _ParentId;
		
		private System.Data.Linq.Binary _DeleteTransactionId;
		
		private System.Guid _WebId;
		
		private System.Nullable<System.Guid> _ListId;
		
		private System.Nullable<int> _DoclibRowId;
		
		private byte _Type;
		
		private byte _SortBehavior;
		
		private System.Nullable<int> _Size;
		
		private System.Nullable<int> _ETagVersion;
		
		private System.Nullable<int> _EffectiveVersion;
		
		private System.Nullable<int> _InternalVersion;
		
		private int _ContentVersion;
		
		private System.Nullable<long> _NextBSN;
		
		private System.Nullable<long> _MetadataNextBSN;
		
		private System.Nullable<byte> _StreamSchema;
		
		private int _HasStream;
		
		private byte _BumpVersion;
		
		private int _UIVersion;
		
		private System.Nullable<bool> _Dirty;
		
		private bool _ListDataDirty;
		
		private System.Nullable<int> _DocFlags;
		
		private System.Nullable<bool> _ThicketFlag;
		
		private System.Nullable<int> _CharSet;
		
		private string _ProgId;
		
		private System.DateTime _TimeCreated;
		
		private System.DateTime _TimeLastModified;
		
		private System.Nullable<System.DateTime> _NextToLastTimeModified;
		
		private System.Nullable<System.DateTime> _MetaInfoTimeLastModified;
		
		private System.Nullable<System.DateTime> _TimeLastWritten;
		
		private byte _SetupPathVersion;
		
		private string _SetupPath;
		
		private string _SetupPathUser;
		
		private System.Nullable<int> _CheckoutUserId;
		
		private System.Nullable<int> _DraftOwnerId;
		
		private System.Nullable<System.DateTime> _CheckoutDate;
		
		private System.Nullable<System.DateTime> _CheckoutExpires;
		
		private bool _VersionCreatedSinceSTCheckout;
		
		private System.Nullable<int> _LTCheckoutUserId;
		
		private string _CheckinComment;
		
		private int _IsCheckoutToLocal;
		
		private System.Nullable<int> _VirusVendorID;
		
		private System.Nullable<byte> _VirusStatus;
		
		private string _VirusInfo;
		
		private System.Data.Linq.Binary _VirusInfoEx;
		
		private System.Data.Linq.Binary _MetaInfo;
		
		private System.Nullable<int> _MetaInfoSize;
		
		private int _MetaInfoVersion;
		
		private System.Data.Linq.Binary _UnVersionedMetaInfo;
		
		private System.Nullable<int> _UnVersionedMetaInfoSize;
		
		private System.Nullable<int> _UnVersionedMetaInfoVersion;
		
		private string _WelcomePageUrl;
		
		private string _WelcomePageParameters;
		
		private bool _IsCurrentVersion;
		
		private System.Nullable<int> _AuditFlags;
		
		private System.Nullable<int> _InheritAuditFlags;
		
		private string _UIVersionString;
		
		private System.Guid _ScopeId;
		
		private System.Data.Linq.Binary _BuildDependencySet;
		
		private System.Nullable<int> _ParentVersion;
		
		private string _ParentVersionString;
		
		private System.Nullable<System.Guid> _TransformerId;
		
		private string _ParentLeafName;
		
		private System.Nullable<short> _CtoOffset;
		
		private string _Extension;
		
		private string _ExtensionForFile;
		
		private int _ItemChildCount;
		
		private int _FolderChildCount;
		
		private System.Data.Linq.Binary _FileFormatMetaInfo;
		
		private int _FileFormatMetaInfoSize;
		
		private System.Nullable<bool> _FFMConsistent;
		
		private System.Nullable<int> _ListSchemaVersion;
		
		private System.Data.Linq.Binary _ClientId;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(System.Guid value);
    partial void OnIdChanged();
    partial void OnSiteIdChanging(System.Guid value);
    partial void OnSiteIdChanged();
    partial void OnDirNameChanging(string value);
    partial void OnDirNameChanged();
    partial void OnLeafNameChanging(string value);
    partial void OnLeafNameChanged();
    partial void OnLevelChanging(byte value);
    partial void OnLevelChanged();
    partial void OnParentIdChanging(System.Guid value);
    partial void OnParentIdChanged();
    partial void OnDeleteTransactionIdChanging(System.Data.Linq.Binary value);
    partial void OnDeleteTransactionIdChanged();
    partial void OnWebIdChanging(System.Guid value);
    partial void OnWebIdChanged();
    partial void OnListIdChanging(System.Nullable<System.Guid> value);
    partial void OnListIdChanged();
    partial void OnDoclibRowIdChanging(System.Nullable<int> value);
    partial void OnDoclibRowIdChanged();
    partial void OnTypeChanging(byte value);
    partial void OnTypeChanged();
    partial void OnSortBehaviorChanging(byte value);
    partial void OnSortBehaviorChanged();
    partial void OnSizeChanging(System.Nullable<int> value);
    partial void OnSizeChanged();
    partial void OnETagVersionChanging(System.Nullable<int> value);
    partial void OnETagVersionChanged();
    partial void OnEffectiveVersionChanging(System.Nullable<int> value);
    partial void OnEffectiveVersionChanged();
    partial void OnInternalVersionChanging(System.Nullable<int> value);
    partial void OnInternalVersionChanged();
    partial void OnContentVersionChanging(int value);
    partial void OnContentVersionChanged();
    partial void OnNextBSNChanging(System.Nullable<long> value);
    partial void OnNextBSNChanged();
    partial void OnMetadataNextBSNChanging(System.Nullable<long> value);
    partial void OnMetadataNextBSNChanged();
    partial void OnStreamSchemaChanging(System.Nullable<byte> value);
    partial void OnStreamSchemaChanged();
    partial void OnHasStreamChanging(int value);
    partial void OnHasStreamChanged();
    partial void OnBumpVersionChanging(byte value);
    partial void OnBumpVersionChanged();
    partial void OnUIVersionChanging(int value);
    partial void OnUIVersionChanged();
    partial void OnDirtyChanging(System.Nullable<bool> value);
    partial void OnDirtyChanged();
    partial void OnListDataDirtyChanging(bool value);
    partial void OnListDataDirtyChanged();
    partial void OnDocFlagsChanging(System.Nullable<int> value);
    partial void OnDocFlagsChanged();
    partial void OnThicketFlagChanging(System.Nullable<bool> value);
    partial void OnThicketFlagChanged();
    partial void OnCharSetChanging(System.Nullable<int> value);
    partial void OnCharSetChanged();
    partial void OnProgIdChanging(string value);
    partial void OnProgIdChanged();
    partial void OnTimeCreatedChanging(System.DateTime value);
    partial void OnTimeCreatedChanged();
    partial void OnTimeLastModifiedChanging(System.DateTime value);
    partial void OnTimeLastModifiedChanged();
    partial void OnNextToLastTimeModifiedChanging(System.Nullable<System.DateTime> value);
    partial void OnNextToLastTimeModifiedChanged();
    partial void OnMetaInfoTimeLastModifiedChanging(System.Nullable<System.DateTime> value);
    partial void OnMetaInfoTimeLastModifiedChanged();
    partial void OnTimeLastWrittenChanging(System.Nullable<System.DateTime> value);
    partial void OnTimeLastWrittenChanged();
    partial void OnSetupPathVersionChanging(byte value);
    partial void OnSetupPathVersionChanged();
    partial void OnSetupPathChanging(string value);
    partial void OnSetupPathChanged();
    partial void OnSetupPathUserChanging(string value);
    partial void OnSetupPathUserChanged();
    partial void OnCheckoutUserIdChanging(System.Nullable<int> value);
    partial void OnCheckoutUserIdChanged();
    partial void OnDraftOwnerIdChanging(System.Nullable<int> value);
    partial void OnDraftOwnerIdChanged();
    partial void OnCheckoutDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCheckoutDateChanged();
    partial void OnCheckoutExpiresChanging(System.Nullable<System.DateTime> value);
    partial void OnCheckoutExpiresChanged();
    partial void OnVersionCreatedSinceSTCheckoutChanging(bool value);
    partial void OnVersionCreatedSinceSTCheckoutChanged();
    partial void OnLTCheckoutUserIdChanging(System.Nullable<int> value);
    partial void OnLTCheckoutUserIdChanged();
    partial void OnCheckinCommentChanging(string value);
    partial void OnCheckinCommentChanged();
    partial void OnIsCheckoutToLocalChanging(int value);
    partial void OnIsCheckoutToLocalChanged();
    partial void OnVirusVendorIDChanging(System.Nullable<int> value);
    partial void OnVirusVendorIDChanged();
    partial void OnVirusStatusChanging(System.Nullable<byte> value);
    partial void OnVirusStatusChanged();
    partial void OnVirusInfoChanging(string value);
    partial void OnVirusInfoChanged();
    partial void OnVirusInfoExChanging(System.Data.Linq.Binary value);
    partial void OnVirusInfoExChanged();
    partial void OnMetaInfoChanging(System.Data.Linq.Binary value);
    partial void OnMetaInfoChanged();
    partial void OnMetaInfoSizeChanging(System.Nullable<int> value);
    partial void OnMetaInfoSizeChanged();
    partial void OnMetaInfoVersionChanging(int value);
    partial void OnMetaInfoVersionChanged();
    partial void OnUnVersionedMetaInfoChanging(System.Data.Linq.Binary value);
    partial void OnUnVersionedMetaInfoChanged();
    partial void OnUnVersionedMetaInfoSizeChanging(System.Nullable<int> value);
    partial void OnUnVersionedMetaInfoSizeChanged();
    partial void OnUnVersionedMetaInfoVersionChanging(System.Nullable<int> value);
    partial void OnUnVersionedMetaInfoVersionChanged();
    partial void OnWelcomePageUrlChanging(string value);
    partial void OnWelcomePageUrlChanged();
    partial void OnWelcomePageParametersChanging(string value);
    partial void OnWelcomePageParametersChanged();
    partial void OnIsCurrentVersionChanging(bool value);
    partial void OnIsCurrentVersionChanged();
    partial void OnAuditFlagsChanging(System.Nullable<int> value);
    partial void OnAuditFlagsChanged();
    partial void OnInheritAuditFlagsChanging(System.Nullable<int> value);
    partial void OnInheritAuditFlagsChanged();
    partial void OnUIVersionStringChanging(string value);
    partial void OnUIVersionStringChanged();
    partial void OnScopeIdChanging(System.Guid value);
    partial void OnScopeIdChanged();
    partial void OnBuildDependencySetChanging(System.Data.Linq.Binary value);
    partial void OnBuildDependencySetChanged();
    partial void OnParentVersionChanging(System.Nullable<int> value);
    partial void OnParentVersionChanged();
    partial void OnParentVersionStringChanging(string value);
    partial void OnParentVersionStringChanged();
    partial void OnTransformerIdChanging(System.Nullable<System.Guid> value);
    partial void OnTransformerIdChanged();
    partial void OnParentLeafNameChanging(string value);
    partial void OnParentLeafNameChanged();
    partial void OnCtoOffsetChanging(System.Nullable<short> value);
    partial void OnCtoOffsetChanged();
    partial void OnExtensionChanging(string value);
    partial void OnExtensionChanged();
    partial void OnExtensionForFileChanging(string value);
    partial void OnExtensionForFileChanged();
    partial void OnItemChildCountChanging(int value);
    partial void OnItemChildCountChanged();
    partial void OnFolderChildCountChanging(int value);
    partial void OnFolderChildCountChanged();
    partial void OnFileFormatMetaInfoChanging(System.Data.Linq.Binary value);
    partial void OnFileFormatMetaInfoChanged();
    partial void OnFileFormatMetaInfoSizeChanging(int value);
    partial void OnFileFormatMetaInfoSizeChanged();
    partial void OnFFMConsistentChanging(System.Nullable<bool> value);
    partial void OnFFMConsistentChanged();
    partial void OnListSchemaVersionChanging(System.Nullable<int> value);
    partial void OnListSchemaVersionChanged();
    partial void OnClientIdChanging(System.Data.Linq.Binary value);
    partial void OnClientIdChanged();
    #endregion
		
		public AllDocs()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SiteId", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid SiteId
		{
			get
			{
				return this._SiteId;
			}
			set
			{
				if ((this._SiteId != value))
				{
					this.OnSiteIdChanging(value);
					this.SendPropertyChanging();
					this._SiteId = value;
					this.SendPropertyChanged("SiteId");
					this.OnSiteIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DirName", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string DirName
		{
			get
			{
				return this._DirName;
			}
			set
			{
				if ((this._DirName != value))
				{
					this.OnDirNameChanging(value);
					this.SendPropertyChanging();
					this._DirName = value;
					this.SendPropertyChanged("DirName");
					this.OnDirNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LeafName", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string LeafName
		{
			get
			{
				return this._LeafName;
			}
			set
			{
				if ((this._LeafName != value))
				{
					this.OnLeafNameChanging(value);
					this.SendPropertyChanging();
					this._LeafName = value;
					this.SendPropertyChanged("LeafName");
					this.OnLeafNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Level]", Storage="_Level", DbType="TinyInt NOT NULL", IsPrimaryKey=true)]
		public byte Level
		{
			get
			{
				return this._Level;
			}
			set
			{
				if ((this._Level != value))
				{
					this.OnLevelChanging(value);
					this.SendPropertyChanging();
					this._Level = value;
					this.SendPropertyChanged("Level");
					this.OnLevelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentId", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid ParentId
		{
			get
			{
				return this._ParentId;
			}
			set
			{
				if ((this._ParentId != value))
				{
					this.OnParentIdChanging(value);
					this.SendPropertyChanging();
					this._ParentId = value;
					this.SendPropertyChanged("ParentId");
					this.OnParentIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeleteTransactionId", DbType="VarBinary(16) NOT NULL", CanBeNull=false, IsPrimaryKey=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary DeleteTransactionId
		{
			get
			{
				return this._DeleteTransactionId;
			}
			set
			{
				if ((this._DeleteTransactionId != value))
				{
					this.OnDeleteTransactionIdChanging(value);
					this.SendPropertyChanging();
					this._DeleteTransactionId = value;
					this.SendPropertyChanged("DeleteTransactionId");
					this.OnDeleteTransactionIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WebId", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid WebId
		{
			get
			{
				return this._WebId;
			}
			set
			{
				if ((this._WebId != value))
				{
					this.OnWebIdChanging(value);
					this.SendPropertyChanging();
					this._WebId = value;
					this.SendPropertyChanged("WebId");
					this.OnWebIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ListId", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> ListId
		{
			get
			{
				return this._ListId;
			}
			set
			{
				if ((this._ListId != value))
				{
					this.OnListIdChanging(value);
					this.SendPropertyChanging();
					this._ListId = value;
					this.SendPropertyChanged("ListId");
					this.OnListIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DoclibRowId", DbType="Int")]
		public System.Nullable<int> DoclibRowId
		{
			get
			{
				return this._DoclibRowId;
			}
			set
			{
				if ((this._DoclibRowId != value))
				{
					this.OnDoclibRowIdChanging(value);
					this.SendPropertyChanging();
					this._DoclibRowId = value;
					this.SendPropertyChanged("DoclibRowId");
					this.OnDoclibRowIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="TinyInt NOT NULL")]
		public byte Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this.OnTypeChanging(value);
					this.SendPropertyChanging();
					this._Type = value;
					this.SendPropertyChanged("Type");
					this.OnTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SortBehavior", DbType="TinyInt NOT NULL")]
		public byte SortBehavior
		{
			get
			{
				return this._SortBehavior;
			}
			set
			{
				if ((this._SortBehavior != value))
				{
					this.OnSortBehaviorChanging(value);
					this.SendPropertyChanging();
					this._SortBehavior = value;
					this.SendPropertyChanged("SortBehavior");
					this.OnSortBehaviorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Size", DbType="Int")]
		public System.Nullable<int> Size
		{
			get
			{
				return this._Size;
			}
			set
			{
				if ((this._Size != value))
				{
					this.OnSizeChanging(value);
					this.SendPropertyChanging();
					this._Size = value;
					this.SendPropertyChanged("Size");
					this.OnSizeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ETagVersion", AutoSync=AutoSync.Always, DbType="Int", IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> ETagVersion
		{
			get
			{
				return this._ETagVersion;
			}
			set
			{
				if ((this._ETagVersion != value))
				{
					this.OnETagVersionChanging(value);
					this.SendPropertyChanging();
					this._ETagVersion = value;
					this.SendPropertyChanged("ETagVersion");
					this.OnETagVersionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EffectiveVersion", AutoSync=AutoSync.Always, DbType="Int", IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> EffectiveVersion
		{
			get
			{
				return this._EffectiveVersion;
			}
			set
			{
				if ((this._EffectiveVersion != value))
				{
					this.OnEffectiveVersionChanging(value);
					this.SendPropertyChanging();
					this._EffectiveVersion = value;
					this.SendPropertyChanged("EffectiveVersion");
					this.OnEffectiveVersionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InternalVersion", DbType="Int")]
		public System.Nullable<int> InternalVersion
		{
			get
			{
				return this._InternalVersion;
			}
			set
			{
				if ((this._InternalVersion != value))
				{
					this.OnInternalVersionChanging(value);
					this.SendPropertyChanging();
					this._InternalVersion = value;
					this.SendPropertyChanged("InternalVersion");
					this.OnInternalVersionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContentVersion", DbType="Int NOT NULL")]
		public int ContentVersion
		{
			get
			{
				return this._ContentVersion;
			}
			set
			{
				if ((this._ContentVersion != value))
				{
					this.OnContentVersionChanging(value);
					this.SendPropertyChanging();
					this._ContentVersion = value;
					this.SendPropertyChanged("ContentVersion");
					this.OnContentVersionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NextBSN", DbType="BigInt")]
		public System.Nullable<long> NextBSN
		{
			get
			{
				return this._NextBSN;
			}
			set
			{
				if ((this._NextBSN != value))
				{
					this.OnNextBSNChanging(value);
					this.SendPropertyChanging();
					this._NextBSN = value;
					this.SendPropertyChanged("NextBSN");
					this.OnNextBSNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MetadataNextBSN", DbType="BigInt")]
		public System.Nullable<long> MetadataNextBSN
		{
			get
			{
				return this._MetadataNextBSN;
			}
			set
			{
				if ((this._MetadataNextBSN != value))
				{
					this.OnMetadataNextBSNChanging(value);
					this.SendPropertyChanging();
					this._MetadataNextBSN = value;
					this.SendPropertyChanged("MetadataNextBSN");
					this.OnMetadataNextBSNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StreamSchema", DbType="TinyInt")]
		public System.Nullable<byte> StreamSchema
		{
			get
			{
				return this._StreamSchema;
			}
			set
			{
				if ((this._StreamSchema != value))
				{
					this.OnStreamSchemaChanging(value);
					this.SendPropertyChanging();
					this._StreamSchema = value;
					this.SendPropertyChanged("StreamSchema");
					this.OnStreamSchemaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HasStream", AutoSync=AutoSync.Always, DbType="Int NOT NULL", IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public int HasStream
		{
			get
			{
				return this._HasStream;
			}
			set
			{
				if ((this._HasStream != value))
				{
					this.OnHasStreamChanging(value);
					this.SendPropertyChanging();
					this._HasStream = value;
					this.SendPropertyChanged("HasStream");
					this.OnHasStreamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BumpVersion", DbType="TinyInt NOT NULL")]
		public byte BumpVersion
		{
			get
			{
				return this._BumpVersion;
			}
			set
			{
				if ((this._BumpVersion != value))
				{
					this.OnBumpVersionChanging(value);
					this.SendPropertyChanging();
					this._BumpVersion = value;
					this.SendPropertyChanged("BumpVersion");
					this.OnBumpVersionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UIVersion", DbType="Int NOT NULL")]
		public int UIVersion
		{
			get
			{
				return this._UIVersion;
			}
			set
			{
				if ((this._UIVersion != value))
				{
					this.OnUIVersionChanging(value);
					this.SendPropertyChanging();
					this._UIVersion = value;
					this.SendPropertyChanged("UIVersion");
					this.OnUIVersionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dirty", AutoSync=AutoSync.Always, DbType="Bit", IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<bool> Dirty
		{
			get
			{
				return this._Dirty;
			}
			set
			{
				if ((this._Dirty != value))
				{
					this.OnDirtyChanging(value);
					this.SendPropertyChanging();
					this._Dirty = value;
					this.SendPropertyChanged("Dirty");
					this.OnDirtyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ListDataDirty", DbType="Bit NOT NULL")]
		public bool ListDataDirty
		{
			get
			{
				return this._ListDataDirty;
			}
			set
			{
				if ((this._ListDataDirty != value))
				{
					this.OnListDataDirtyChanging(value);
					this.SendPropertyChanging();
					this._ListDataDirty = value;
					this.SendPropertyChanged("ListDataDirty");
					this.OnListDataDirtyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DocFlags", DbType="Int")]
		public System.Nullable<int> DocFlags
		{
			get
			{
				return this._DocFlags;
			}
			set
			{
				if ((this._DocFlags != value))
				{
					this.OnDocFlagsChanging(value);
					this.SendPropertyChanging();
					this._DocFlags = value;
					this.SendPropertyChanged("DocFlags");
					this.OnDocFlagsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThicketFlag", DbType="Bit")]
		public System.Nullable<bool> ThicketFlag
		{
			get
			{
				return this._ThicketFlag;
			}
			set
			{
				if ((this._ThicketFlag != value))
				{
					this.OnThicketFlagChanging(value);
					this.SendPropertyChanging();
					this._ThicketFlag = value;
					this.SendPropertyChanged("ThicketFlag");
					this.OnThicketFlagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CharSet", DbType="Int")]
		public System.Nullable<int> CharSet
		{
			get
			{
				return this._CharSet;
			}
			set
			{
				if ((this._CharSet != value))
				{
					this.OnCharSetChanging(value);
					this.SendPropertyChanging();
					this._CharSet = value;
					this.SendPropertyChanged("CharSet");
					this.OnCharSetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProgId", DbType="NVarChar(255)")]
		public string ProgId
		{
			get
			{
				return this._ProgId;
			}
			set
			{
				if ((this._ProgId != value))
				{
					this.OnProgIdChanging(value);
					this.SendPropertyChanging();
					this._ProgId = value;
					this.SendPropertyChanged("ProgId");
					this.OnProgIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeCreated", DbType="DateTime NOT NULL")]
		public System.DateTime TimeCreated
		{
			get
			{
				return this._TimeCreated;
			}
			set
			{
				if ((this._TimeCreated != value))
				{
					this.OnTimeCreatedChanging(value);
					this.SendPropertyChanging();
					this._TimeCreated = value;
					this.SendPropertyChanged("TimeCreated");
					this.OnTimeCreatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeLastModified", DbType="DateTime NOT NULL")]
		public System.DateTime TimeLastModified
		{
			get
			{
				return this._TimeLastModified;
			}
			set
			{
				if ((this._TimeLastModified != value))
				{
					this.OnTimeLastModifiedChanging(value);
					this.SendPropertyChanging();
					this._TimeLastModified = value;
					this.SendPropertyChanged("TimeLastModified");
					this.OnTimeLastModifiedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NextToLastTimeModified", DbType="DateTime")]
		public System.Nullable<System.DateTime> NextToLastTimeModified
		{
			get
			{
				return this._NextToLastTimeModified;
			}
			set
			{
				if ((this._NextToLastTimeModified != value))
				{
					this.OnNextToLastTimeModifiedChanging(value);
					this.SendPropertyChanging();
					this._NextToLastTimeModified = value;
					this.SendPropertyChanged("NextToLastTimeModified");
					this.OnNextToLastTimeModifiedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MetaInfoTimeLastModified", DbType="DateTime")]
		public System.Nullable<System.DateTime> MetaInfoTimeLastModified
		{
			get
			{
				return this._MetaInfoTimeLastModified;
			}
			set
			{
				if ((this._MetaInfoTimeLastModified != value))
				{
					this.OnMetaInfoTimeLastModifiedChanging(value);
					this.SendPropertyChanging();
					this._MetaInfoTimeLastModified = value;
					this.SendPropertyChanged("MetaInfoTimeLastModified");
					this.OnMetaInfoTimeLastModifiedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeLastWritten", DbType="DateTime")]
		public System.Nullable<System.DateTime> TimeLastWritten
		{
			get
			{
				return this._TimeLastWritten;
			}
			set
			{
				if ((this._TimeLastWritten != value))
				{
					this.OnTimeLastWrittenChanging(value);
					this.SendPropertyChanging();
					this._TimeLastWritten = value;
					this.SendPropertyChanged("TimeLastWritten");
					this.OnTimeLastWrittenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SetupPathVersion", DbType="TinyInt NOT NULL")]
		public byte SetupPathVersion
		{
			get
			{
				return this._SetupPathVersion;
			}
			set
			{
				if ((this._SetupPathVersion != value))
				{
					this.OnSetupPathVersionChanging(value);
					this.SendPropertyChanging();
					this._SetupPathVersion = value;
					this.SendPropertyChanged("SetupPathVersion");
					this.OnSetupPathVersionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SetupPath", DbType="NVarChar(255)")]
		public string SetupPath
		{
			get
			{
				return this._SetupPath;
			}
			set
			{
				if ((this._SetupPath != value))
				{
					this.OnSetupPathChanging(value);
					this.SendPropertyChanging();
					this._SetupPath = value;
					this.SendPropertyChanged("SetupPath");
					this.OnSetupPathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SetupPathUser", DbType="NVarChar(255)")]
		public string SetupPathUser
		{
			get
			{
				return this._SetupPathUser;
			}
			set
			{
				if ((this._SetupPathUser != value))
				{
					this.OnSetupPathUserChanging(value);
					this.SendPropertyChanging();
					this._SetupPathUser = value;
					this.SendPropertyChanged("SetupPathUser");
					this.OnSetupPathUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CheckoutUserId", DbType="Int")]
		public System.Nullable<int> CheckoutUserId
		{
			get
			{
				return this._CheckoutUserId;
			}
			set
			{
				if ((this._CheckoutUserId != value))
				{
					this.OnCheckoutUserIdChanging(value);
					this.SendPropertyChanging();
					this._CheckoutUserId = value;
					this.SendPropertyChanged("CheckoutUserId");
					this.OnCheckoutUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DraftOwnerId", DbType="Int")]
		public System.Nullable<int> DraftOwnerId
		{
			get
			{
				return this._DraftOwnerId;
			}
			set
			{
				if ((this._DraftOwnerId != value))
				{
					this.OnDraftOwnerIdChanging(value);
					this.SendPropertyChanging();
					this._DraftOwnerId = value;
					this.SendPropertyChanged("DraftOwnerId");
					this.OnDraftOwnerIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CheckoutDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CheckoutDate
		{
			get
			{
				return this._CheckoutDate;
			}
			set
			{
				if ((this._CheckoutDate != value))
				{
					this.OnCheckoutDateChanging(value);
					this.SendPropertyChanging();
					this._CheckoutDate = value;
					this.SendPropertyChanged("CheckoutDate");
					this.OnCheckoutDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CheckoutExpires", DbType="DateTime")]
		public System.Nullable<System.DateTime> CheckoutExpires
		{
			get
			{
				return this._CheckoutExpires;
			}
			set
			{
				if ((this._CheckoutExpires != value))
				{
					this.OnCheckoutExpiresChanging(value);
					this.SendPropertyChanging();
					this._CheckoutExpires = value;
					this.SendPropertyChanged("CheckoutExpires");
					this.OnCheckoutExpiresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VersionCreatedSinceSTCheckout", DbType="Bit NOT NULL")]
		public bool VersionCreatedSinceSTCheckout
		{
			get
			{
				return this._VersionCreatedSinceSTCheckout;
			}
			set
			{
				if ((this._VersionCreatedSinceSTCheckout != value))
				{
					this.OnVersionCreatedSinceSTCheckoutChanging(value);
					this.SendPropertyChanging();
					this._VersionCreatedSinceSTCheckout = value;
					this.SendPropertyChanged("VersionCreatedSinceSTCheckout");
					this.OnVersionCreatedSinceSTCheckoutChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LTCheckoutUserId", AutoSync=AutoSync.Always, DbType="Int", IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> LTCheckoutUserId
		{
			get
			{
				return this._LTCheckoutUserId;
			}
			set
			{
				if ((this._LTCheckoutUserId != value))
				{
					this.OnLTCheckoutUserIdChanging(value);
					this.SendPropertyChanging();
					this._LTCheckoutUserId = value;
					this.SendPropertyChanged("LTCheckoutUserId");
					this.OnLTCheckoutUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CheckinComment", DbType="NVarChar(1023)")]
		public string CheckinComment
		{
			get
			{
				return this._CheckinComment;
			}
			set
			{
				if ((this._CheckinComment != value))
				{
					this.OnCheckinCommentChanging(value);
					this.SendPropertyChanging();
					this._CheckinComment = value;
					this.SendPropertyChanged("CheckinComment");
					this.OnCheckinCommentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsCheckoutToLocal", AutoSync=AutoSync.Always, DbType="Int NOT NULL", IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public int IsCheckoutToLocal
		{
			get
			{
				return this._IsCheckoutToLocal;
			}
			set
			{
				if ((this._IsCheckoutToLocal != value))
				{
					this.OnIsCheckoutToLocalChanging(value);
					this.SendPropertyChanging();
					this._IsCheckoutToLocal = value;
					this.SendPropertyChanged("IsCheckoutToLocal");
					this.OnIsCheckoutToLocalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VirusVendorID", DbType="Int")]
		public System.Nullable<int> VirusVendorID
		{
			get
			{
				return this._VirusVendorID;
			}
			set
			{
				if ((this._VirusVendorID != value))
				{
					this.OnVirusVendorIDChanging(value);
					this.SendPropertyChanging();
					this._VirusVendorID = value;
					this.SendPropertyChanged("VirusVendorID");
					this.OnVirusVendorIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VirusStatus", DbType="TinyInt")]
		public System.Nullable<byte> VirusStatus
		{
			get
			{
				return this._VirusStatus;
			}
			set
			{
				if ((this._VirusStatus != value))
				{
					this.OnVirusStatusChanging(value);
					this.SendPropertyChanging();
					this._VirusStatus = value;
					this.SendPropertyChanged("VirusStatus");
					this.OnVirusStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VirusInfo", DbType="NVarChar(255)")]
		public string VirusInfo
		{
			get
			{
				return this._VirusInfo;
			}
			set
			{
				if ((this._VirusInfo != value))
				{
					this.OnVirusInfoChanging(value);
					this.SendPropertyChanging();
					this._VirusInfo = value;
					this.SendPropertyChanged("VirusInfo");
					this.OnVirusInfoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VirusInfoEx", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary VirusInfoEx
		{
			get
			{
				return this._VirusInfoEx;
			}
			set
			{
				if ((this._VirusInfoEx != value))
				{
					this.OnVirusInfoExChanging(value);
					this.SendPropertyChanging();
					this._VirusInfoEx = value;
					this.SendPropertyChanged("VirusInfoEx");
					this.OnVirusInfoExChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MetaInfo", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary MetaInfo
		{
			get
			{
				return this._MetaInfo;
			}
			set
			{
				if ((this._MetaInfo != value))
				{
					this.OnMetaInfoChanging(value);
					this.SendPropertyChanging();
					this._MetaInfo = value;
					this.SendPropertyChanged("MetaInfo");
					this.OnMetaInfoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MetaInfoSize", DbType="Int")]
		public System.Nullable<int> MetaInfoSize
		{
			get
			{
				return this._MetaInfoSize;
			}
			set
			{
				if ((this._MetaInfoSize != value))
				{
					this.OnMetaInfoSizeChanging(value);
					this.SendPropertyChanging();
					this._MetaInfoSize = value;
					this.SendPropertyChanged("MetaInfoSize");
					this.OnMetaInfoSizeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MetaInfoVersion", DbType="Int NOT NULL")]
		public int MetaInfoVersion
		{
			get
			{
				return this._MetaInfoVersion;
			}
			set
			{
				if ((this._MetaInfoVersion != value))
				{
					this.OnMetaInfoVersionChanging(value);
					this.SendPropertyChanging();
					this._MetaInfoVersion = value;
					this.SendPropertyChanged("MetaInfoVersion");
					this.OnMetaInfoVersionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnVersionedMetaInfo", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary UnVersionedMetaInfo
		{
			get
			{
				return this._UnVersionedMetaInfo;
			}
			set
			{
				if ((this._UnVersionedMetaInfo != value))
				{
					this.OnUnVersionedMetaInfoChanging(value);
					this.SendPropertyChanging();
					this._UnVersionedMetaInfo = value;
					this.SendPropertyChanged("UnVersionedMetaInfo");
					this.OnUnVersionedMetaInfoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnVersionedMetaInfoSize", DbType="Int")]
		public System.Nullable<int> UnVersionedMetaInfoSize
		{
			get
			{
				return this._UnVersionedMetaInfoSize;
			}
			set
			{
				if ((this._UnVersionedMetaInfoSize != value))
				{
					this.OnUnVersionedMetaInfoSizeChanging(value);
					this.SendPropertyChanging();
					this._UnVersionedMetaInfoSize = value;
					this.SendPropertyChanged("UnVersionedMetaInfoSize");
					this.OnUnVersionedMetaInfoSizeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnVersionedMetaInfoVersion", DbType="Int")]
		public System.Nullable<int> UnVersionedMetaInfoVersion
		{
			get
			{
				return this._UnVersionedMetaInfoVersion;
			}
			set
			{
				if ((this._UnVersionedMetaInfoVersion != value))
				{
					this.OnUnVersionedMetaInfoVersionChanging(value);
					this.SendPropertyChanging();
					this._UnVersionedMetaInfoVersion = value;
					this.SendPropertyChanged("UnVersionedMetaInfoVersion");
					this.OnUnVersionedMetaInfoVersionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WelcomePageUrl", DbType="NVarChar(260)")]
		public string WelcomePageUrl
		{
			get
			{
				return this._WelcomePageUrl;
			}
			set
			{
				if ((this._WelcomePageUrl != value))
				{
					this.OnWelcomePageUrlChanging(value);
					this.SendPropertyChanging();
					this._WelcomePageUrl = value;
					this.SendPropertyChanged("WelcomePageUrl");
					this.OnWelcomePageUrlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WelcomePageParameters", DbType="NVarChar(MAX)")]
		public string WelcomePageParameters
		{
			get
			{
				return this._WelcomePageParameters;
			}
			set
			{
				if ((this._WelcomePageParameters != value))
				{
					this.OnWelcomePageParametersChanging(value);
					this.SendPropertyChanging();
					this._WelcomePageParameters = value;
					this.SendPropertyChanged("WelcomePageParameters");
					this.OnWelcomePageParametersChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsCurrentVersion", DbType="Bit NOT NULL")]
		public bool IsCurrentVersion
		{
			get
			{
				return this._IsCurrentVersion;
			}
			set
			{
				if ((this._IsCurrentVersion != value))
				{
					this.OnIsCurrentVersionChanging(value);
					this.SendPropertyChanging();
					this._IsCurrentVersion = value;
					this.SendPropertyChanged("IsCurrentVersion");
					this.OnIsCurrentVersionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AuditFlags", DbType="Int")]
		public System.Nullable<int> AuditFlags
		{
			get
			{
				return this._AuditFlags;
			}
			set
			{
				if ((this._AuditFlags != value))
				{
					this.OnAuditFlagsChanging(value);
					this.SendPropertyChanging();
					this._AuditFlags = value;
					this.SendPropertyChanged("AuditFlags");
					this.OnAuditFlagsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InheritAuditFlags", DbType="Int")]
		public System.Nullable<int> InheritAuditFlags
		{
			get
			{
				return this._InheritAuditFlags;
			}
			set
			{
				if ((this._InheritAuditFlags != value))
				{
					this.OnInheritAuditFlagsChanging(value);
					this.SendPropertyChanging();
					this._InheritAuditFlags = value;
					this.SendPropertyChanged("InheritAuditFlags");
					this.OnInheritAuditFlagsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UIVersionString", AutoSync=AutoSync.Always, DbType="NVarChar(61)", IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public string UIVersionString
		{
			get
			{
				return this._UIVersionString;
			}
			set
			{
				if ((this._UIVersionString != value))
				{
					this.OnUIVersionStringChanging(value);
					this.SendPropertyChanging();
					this._UIVersionString = value;
					this.SendPropertyChanged("UIVersionString");
					this.OnUIVersionStringChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ScopeId", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid ScopeId
		{
			get
			{
				return this._ScopeId;
			}
			set
			{
				if ((this._ScopeId != value))
				{
					this.OnScopeIdChanging(value);
					this.SendPropertyChanging();
					this._ScopeId = value;
					this.SendPropertyChanged("ScopeId");
					this.OnScopeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BuildDependencySet", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary BuildDependencySet
		{
			get
			{
				return this._BuildDependencySet;
			}
			set
			{
				if ((this._BuildDependencySet != value))
				{
					this.OnBuildDependencySetChanging(value);
					this.SendPropertyChanging();
					this._BuildDependencySet = value;
					this.SendPropertyChanged("BuildDependencySet");
					this.OnBuildDependencySetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentVersion", DbType="Int")]
		public System.Nullable<int> ParentVersion
		{
			get
			{
				return this._ParentVersion;
			}
			set
			{
				if ((this._ParentVersion != value))
				{
					this.OnParentVersionChanging(value);
					this.SendPropertyChanging();
					this._ParentVersion = value;
					this.SendPropertyChanged("ParentVersion");
					this.OnParentVersionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentVersionString", AutoSync=AutoSync.Always, DbType="NVarChar(61)", IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public string ParentVersionString
		{
			get
			{
				return this._ParentVersionString;
			}
			set
			{
				if ((this._ParentVersionString != value))
				{
					this.OnParentVersionStringChanging(value);
					this.SendPropertyChanging();
					this._ParentVersionString = value;
					this.SendPropertyChanged("ParentVersionString");
					this.OnParentVersionStringChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransformerId", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> TransformerId
		{
			get
			{
				return this._TransformerId;
			}
			set
			{
				if ((this._TransformerId != value))
				{
					this.OnTransformerIdChanging(value);
					this.SendPropertyChanging();
					this._TransformerId = value;
					this.SendPropertyChanged("TransformerId");
					this.OnTransformerIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentLeafName", DbType="NVarChar(128)")]
		public string ParentLeafName
		{
			get
			{
				return this._ParentLeafName;
			}
			set
			{
				if ((this._ParentLeafName != value))
				{
					this.OnParentLeafNameChanging(value);
					this.SendPropertyChanging();
					this._ParentLeafName = value;
					this.SendPropertyChanged("ParentLeafName");
					this.OnParentLeafNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CtoOffset", DbType="SmallInt")]
		public System.Nullable<short> CtoOffset
		{
			get
			{
				return this._CtoOffset;
			}
			set
			{
				if ((this._CtoOffset != value))
				{
					this.OnCtoOffsetChanging(value);
					this.SendPropertyChanging();
					this._CtoOffset = value;
					this.SendPropertyChanged("CtoOffset");
					this.OnCtoOffsetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Extension", AutoSync=AutoSync.Always, DbType="NVarChar(128)", IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public string Extension
		{
			get
			{
				return this._Extension;
			}
			set
			{
				if ((this._Extension != value))
				{
					this.OnExtensionChanging(value);
					this.SendPropertyChanging();
					this._Extension = value;
					this.SendPropertyChanged("Extension");
					this.OnExtensionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExtensionForFile", AutoSync=AutoSync.Always, DbType="NVarChar(128)", IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public string ExtensionForFile
		{
			get
			{
				return this._ExtensionForFile;
			}
			set
			{
				if ((this._ExtensionForFile != value))
				{
					this.OnExtensionForFileChanging(value);
					this.SendPropertyChanging();
					this._ExtensionForFile = value;
					this.SendPropertyChanged("ExtensionForFile");
					this.OnExtensionForFileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemChildCount", DbType="Int NOT NULL")]
		public int ItemChildCount
		{
			get
			{
				return this._ItemChildCount;
			}
			set
			{
				if ((this._ItemChildCount != value))
				{
					this.OnItemChildCountChanging(value);
					this.SendPropertyChanging();
					this._ItemChildCount = value;
					this.SendPropertyChanged("ItemChildCount");
					this.OnItemChildCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FolderChildCount", DbType="Int NOT NULL")]
		public int FolderChildCount
		{
			get
			{
				return this._FolderChildCount;
			}
			set
			{
				if ((this._FolderChildCount != value))
				{
					this.OnFolderChildCountChanging(value);
					this.SendPropertyChanging();
					this._FolderChildCount = value;
					this.SendPropertyChanged("FolderChildCount");
					this.OnFolderChildCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileFormatMetaInfo", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary FileFormatMetaInfo
		{
			get
			{
				return this._FileFormatMetaInfo;
			}
			set
			{
				if ((this._FileFormatMetaInfo != value))
				{
					this.OnFileFormatMetaInfoChanging(value);
					this.SendPropertyChanging();
					this._FileFormatMetaInfo = value;
					this.SendPropertyChanged("FileFormatMetaInfo");
					this.OnFileFormatMetaInfoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileFormatMetaInfoSize", DbType="Int NOT NULL")]
		public int FileFormatMetaInfoSize
		{
			get
			{
				return this._FileFormatMetaInfoSize;
			}
			set
			{
				if ((this._FileFormatMetaInfoSize != value))
				{
					this.OnFileFormatMetaInfoSizeChanging(value);
					this.SendPropertyChanging();
					this._FileFormatMetaInfoSize = value;
					this.SendPropertyChanged("FileFormatMetaInfoSize");
					this.OnFileFormatMetaInfoSizeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FFMConsistent", DbType="Bit")]
		public System.Nullable<bool> FFMConsistent
		{
			get
			{
				return this._FFMConsistent;
			}
			set
			{
				if ((this._FFMConsistent != value))
				{
					this.OnFFMConsistentChanging(value);
					this.SendPropertyChanging();
					this._FFMConsistent = value;
					this.SendPropertyChanged("FFMConsistent");
					this.OnFFMConsistentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ListSchemaVersion", DbType="Int")]
		public System.Nullable<int> ListSchemaVersion
		{
			get
			{
				return this._ListSchemaVersion;
			}
			set
			{
				if ((this._ListSchemaVersion != value))
				{
					this.OnListSchemaVersionChanging(value);
					this.SendPropertyChanging();
					this._ListSchemaVersion = value;
					this.SendPropertyChanged("ListSchemaVersion");
					this.OnListSchemaVersionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClientId", DbType="VarBinary(16)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary ClientId
		{
			get
			{
				return this._ClientId;
			}
			set
			{
				if ((this._ClientId != value))
				{
					this.OnClientIdChanging(value);
					this.SendPropertyChanging();
					this._ClientId = value;
					this.SendPropertyChanged("ClientId");
					this.OnClientIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
